import React, { useState } from 'react'
import Head from 'next/head'
import Header from '@/src/components/header/Header'
import MobileNav from '@/src/components/sidebar-nav/MobileNav'
import ProductDetails from '@/src/components/product-details/ProductDetails'


export default function Home() {
    const [openMenu, setOpenMenu] = useState<boolean>(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {openMenu && <MobileNav setOpenMenu={setOpenMenu}/>}
      <Header setOpenMenu={setOpenMenu}/>
      <ProductDetails />
    </>
  )
}
