import React from 'react'
import Head from 'next/head'
import useWindowResize from '@/src/lib/useWindowResize'
import Header from '@/src/components/header/Header'
import useCart from '@/src/context/cartContext'
import MobileNav from '@/src/components/sidebar-nav/MobileNav'
import ProductDetails from '@/src/components/product-details/ProductDetails'


export default function Home() {
  const { innerWidth } = useWindowResize()
  const { openMenu } = useCart()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max__width__wrapper">
        {openMenu && innerWidth! < 768 && <MobileNav />}
        <Header />
        <ProductDetails />
      </div>
    </>
  )
}
